# This workflow will build and deploy unify framework

name: Deploy Unify Framework

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 1.8
      uses: actions/setup-java@v4
      with:
        java-version: 8
        distribution: 'temurin'
        cache: maven
        
    - name: Setup Maven Version
      uses: s4u/setup-maven-action@v1.18.0
      with:
        java-version: 8
        maven-version: 3.5.4
        
    - name: Reconfigure Maven Settings
      uses: whelk-io/maven-settings-xml-action@v20
      with:
        servers: |
          [{
              "id": "sonatype-nexus-snapshots",
              "username": "${{ secrets.REPO_USERNAME }}",
              "password": "${{ secrets.REPO_PASSWORD }}"
          },{
            "id": "sonatype-nexus-staging",
            "username": "${{ secrets.REPO_USERNAME }}",
            "password": "${{ secrets.REPO_PASSWORD }}"
            }] 
          
    - name: Import GPG Key
      uses: crazy-max/ghaction-import-gpg@v1
      env:
        GPG_PRIVATE_KEY: ${{ secrets.MVN_GPG_SECRET_KEY }}
        PASSPHRASE: ${{ secrets.MVN_GPG_PASSPHRASE }} 
    
    - name: Deploy with Maven
      run: mvn clean deploy -B -DrepoDeployMode=true
